services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5002:5000"
    # Use array form to avoid quoting/spacing issues
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - sqlite:////mlflow/mlflow.db
      - --artifacts-destination
      - /mlartifacts
    volumes:
      - ./mlflow.db:/mlflow/mlflow.db
      - ./mlartifacts:/mlartifacts